routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', ['as' => 'login.page.show', 'uses' => 'AuthController@loginPage']);
Route::post('login', ['as' => 'login.page.do', 'uses' => 'AuthController@loginAttempt']);
Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
/*
|--------------------------------------------------------------------------
| Dash Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::get('/', 'HomeController@index');
/*
/*
|--------------------------------------------------------------------------
| Permission Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('permissions', 'PermissionsController');
/*
|--------------------------------------------------------------------------
| Roles Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('roles', 'RolesController');
/*
|--------------------------------------------------------------------------
| Users Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('users', 'UsersController');
/*
|--------------------------------------------------------------------------
| Cities Routes
|--------------------------------------------------------------------------
*/
Route::resource('departments/{department_id}/cities', 'CitiesController');
/*
|--------------------------------------------------------------------------
| Departments Routes
|--------------------------------------------------------------------------
*/
Route::resource('departments', 'DepartmentsController');

/*
|--------------------------------------------------------------------------
| Clients Routes
|--------------------------------------------------------------------------
*/
Route::get('clients/{id}/toggle/', 'ClientsController@toggleClients')->name("clients.toggle");
Route::get('clients/get_client_code', 'ClientsController@getLastClientCode');
Route::post('clients/add_sales', 'ClientsController@addClientBySale');
Route::get('clients/search/{idnum}', 'ClientsController@searchClient');
Route::resource('clients', 'ClientsController');
/*
|--------------------------------------------------------------------------
| Brands Routes
|--------------------------------------------------------------------------
*/
Route::resource('brands', 'BrandsController');
/*
|--------------------------------------------------------------------------
| Metrics Units Routes
|--------------------------------------------------------------------------
*/
Route::resource('metrics', 'MetricsController');
/*
|--------------------------------------------------------------------------
| Categories Routes
|--------------------------------------------------------------------------
*/
Route::resource('categories', 'CategoriesController');
/*
|--------------------------------------------------------------------------
| Providers Routes
|--------------------------------------------------------------------------
*/
Route::get('providers/search/{id}', 'ProvidersController@searchProvider');
Route::resource('providers', 'ProvidersController');
/*
|--------------------------------------------------------------------------
| Products Routes
|--------------------------------------------------------------------------
*/
Route::get("products/find_price/{id}/{list_id}", 'ProductsController@findSellProductsDetails');
Route::get('products/find_product/{id}', 'ProductsController@findProductDetails');
Route::resource('products', 'ProductsController');
/*
|--------------------------------------------------------------------------
| Pricing List Routes
|--------------------------------------------------------------------------
*/
Route::post('all_products', ['as' => 'all.products', 'uses' => 'PricingListController@salesProducts']);
Route::patch('pricing/update', 'PricingListController@updateList');
Route::resource('pricing', 'PricingListController');
/*
|--------------------------------------------------------------------------
| Branches Routes
|--------------------------------------------------------------------------
*/
Route::resource('branches', 'BranchesController');
/*
|--------------------------------------------------------------------------
| Payments Form Routes
|--------------------------------------------------------------------------
*/
Route::resource('payments_forms', 'PaymentsFormController');
/*
|--------------------------------------------------------------------------
| Currencies Routes
|--------------------------------------------------------------------------
*/
Route::resource('currencies', 'CurrenciesController');
/*
|--------------------------------------------------------------------------
| Purchases Routes
|--------------------------------------------------------------------------
*/
Route::post('purchases/payments/submit', ['as' => 'purchases.voucher.submit', 'uses' => 'PurchasesController@paymentVouchersConfirmationSubmit']);
Route::post('purchases/payments/confirmation', ['as' => 'purchases.payments.confirmation', 'uses' => 'PurchasesController@paymentVouchersConfirmation']);
Route::get('purchases/payments', ['as' => 'purchases.payments', 'uses' => 'PurchasesController@paymentVouchers']);
Route::get('purchases/{id}/voucher/cancel', ['as' => 'purchases.voucher.cancel', 'uses' => 'PurchasesController@cancelVoucher']);
Route::post('purchases/{id}/voucher', ['as' => 'purchases.voucher', 'uses' => 'PurchasesController@registerVoucherPayment']);
Route::get('purchases/{id}/voucher', ['as' => 'purchases.voucher.show', 'uses' => 'PurchasesController@showRegisterVoucher']);
Route::resource('purchases', 'PurchasesController');
/*
|--------------------------------------------------------------------------
| Stock Routes
|--------------------------------------------------------------------------
*/
Route::post("stocks/update", 'StocksController@stockAdjustment');
Route::resource('stocks', 'StocksController', ['except' => 'show']);
/*
|--------------------------------------------------------------------------
| Selling Routes
|--------------------------------------------------------------------------
*/
Route::get('sales/create2', 'SalesController@newSalesMethod')->name('sales.create.two');
Route::post('sales/payments/submit', ['as' => 'sales.voucher.submit', 'uses' => 'SalesController@paymentVouchersConfirmationSubmit']);
Route::post('sales/payments/confirmation', ['as' => 'sales.payments.confirmation', 'uses' => 'SalesController@paymentVouchersConfirmation']);
Route::get('sales/payments', ['as' => 'sales.payments', 'uses' => 'SalesController@paymentVouchers']);
Route::get('sales/{id}/voucher/cancel', ['as' => 'sales.voucher.cancel', 'uses' => 'SalesController@cancelVoucher']);
Route::get('sales/{id}/refund', ['as' => 'sales.refund', 'uses' => 'SalesController@showSalesRefund']);
Route::post('sales/{id}/refund', ['as' => 'sales.refund.do', 'uses' => 'SalesController@doSalesRefund']);
Route::post('sales/{id}/voucher', ['as' => 'sales.voucher', 'uses' => 'SalesController@registerVoucherPayment']);
Route::get('sales/{id}/voucher', ['as' => 'sales.voucher.show', 'uses' => 'SalesController@showRegisterVoucher']);
Route::get('sales/print/{id}', ['as' => 'sales.print', 'uses' => 'SalesController@printInvoice']);
Route::resource('sales', 'SalesController');
/*
|--------------------------------------------------------------------------
| Companies Routes
|--------------------------------------------------------------------------
*/
Route::get('companies/get_number/{id}', 'CompaniesController@getNumber');
Route::resource('companies', 'CompaniesController');

/*
|--------------------------------------------------------------------------
| Reports Routes
|--------------------------------------------------------------------------
*/
Route::get('reports/purchases/', ['as' => 'reports.purchases', 'uses' => 'ReportsController@purchases']);
Route::get('reports/refunds/', ['as' => 'reports.refunds', 'uses' => 'ReportsController@refunds']);
Route::get('reports/pricing/', ['as' => 'reports.pricing', 'uses' => 'ReportsController@pricing']);
Route::get('reports/products/', ['as' => 'reports.products.all', 'uses' => 'ReportsController@allProducts']);
Route::get('reports/providers/credit', ['as' => 'reports.providers.credit', 'uses' => 'ReportsController@providersWithCredit']);
Route::get('reports/clients/credit', ['as' => 'reports.clients.credit', 'uses' => 'ReportsController@clientsWithCredit']);
Route::get('reports/products/provider', ['as' => 'reports.products.provider', 'uses' => 'ReportsController@productsByProvider']);
Route::get('reports', ['as' => 'reports.index', 'uses' => 'ReportsController@index']);
Route::get('reports/sales', ['as' => 'reports.sales', 'uses' => 'ReportsController@sales']);
Route::get('reports/day', ['as' => 'reports.sales.day', 'uses' => 'ReportsController@daySales']);
Route::get('reports/products/history', ['as' => 'reports.products.history', 'uses' => 'ReportsController@productHistory']);
Route::get('reports/sales/day', ['as' => 'reports.sales.day', 'uses' => 'ReportsController@daySales']);
Route::get('reports/salesman/commissions', ['as' => 'reports.salesman.commissions', 'uses' => 'ReportsController@getSalesmanCommissions']);
Route::get('reports/users/commissions', ['as' => 'reports.users.commissions', 'uses' => 'ReportsController@getUsersCommissions']);

app/Models/Clients.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Clients extends Model
{

    protected $table = 'clients';

    protected $fillable = ['client_code', 'description', 'idnum', 'tax_name', 'tax_code', 'address',
        'telephone', 'city_id', 'active', 'credit_limit', 'credit_available'
    ];

    public function myCity()
    {
        return $this->belongsTo('App\Models\Cities', 'city_id');
    }

}

resources/views/clients/create.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="{{ url('/') }}">Inicio</a></li>
            <li><a href="{{ route('clients.index') }}">Clientes</a></li>
            <li class="active">Nuevo</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Nuevo Cliente</strong>
                    </div>
                    <div class="card-body">
                        <!-- Credit Card -->
                        <div id="pay-invoice">
                            <div class="card-body">
                                {!! Form::open(['route' => ['clients.store', 'method' => 'post']]) !!}
                                @include('clients.partials.fields')
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-paper-plane-o"></i>&nbsp;
                                        <span id="payment-button-amount">Guardar</span>
                                    </button>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>

                    </div>
                </div> <!-- .card -->

            </div><!--/.col-->
        </div>
    </div>

@endsection


@section('css')
    <link rel="stylesheet" href="{{ '/assets/css/selectize.css' }}">
@endsection

@section('js')
    <script type="text/javascript" src="{{ '/assets/js/selectize.js' }}"></script>
    <script>
        $('#select-city').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $citiesJson !!}
        });
    </script>

@endsection

resources/views/clients/edit.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="{{ url('/') }}">Inicio</a></li>
            <li><a href="{{ route('clients.index') }}">Clientes</a></li>
            <li class="active">Editar</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Editar Cliente</strong>
                    </div>
                    <div class="card-body">
                        <!-- Credit Card -->
                        <div id="pay-invoice">
                            <div class="card-body">
                                {!! Form::model($client, ['route' => ['clients.update', $client->id], 'method' => 'patch']) !!}
                                    @include('clients.partials.fields')
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-paper-plane-o"></i>&nbsp;
                                        <span id="payment-button-amount">Guardar</span>
                                    </button>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>

                    </div>
                </div> <!-- .card -->

            </div><!--/.col-->
        </div>
    </div>

@endsection


@section('css')
    <link rel="stylesheet" href="{{ '/assets/css/selectize.css' }}">
@endsection

@section('js')
    <script type="text/javascript" src="{{ '/assets/js/selectize.js' }}"></script>
    <script>
        $('#select-city').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $citiesJson !!}
        });
    </script>

@endsection

resources/views/clients/index.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="{{ url('/') }}">Inicio</a></li>
            <li><a href="{{ route('clients.index') }}">Clientes</a></li>
            <li class="active">Todos</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">


        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="col-md-11">
                            <strong class="card-title">Filtros de Busqueda</strong>
                        </div>
                        <div class="col-md-1">
                            <a href="{{ route('clients.create') }}">
                                <button class="btn btn-danger btn-sm">
                                    <i class="fa fa-plus"></i> Nuevo
                                </button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('clients.index') }}">
                            <input type="hidden" name="q" value="q">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="cc-payment" class="control-label mb-1">Nombre</label>
                                        {!! Form::text('description', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-success btn-sm">
                                        <i class="fa fa-search"></i> Filtrar
                                    </button>
                                    <a href="{{ route('clients.index') }}" class="btn btn-warning btn-sm"><i class="fa fa-reply-all"></i> Ver Todos</a>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="col-md-11">
                            <strong class="card-title">Clientes</strong>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Razon Social</th>
                                <th scope="col">Ruc</th>
                                <th scope="col">Creado</th>
                                <th scope="col">Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($clients as $client)
                                <tr data-id="{{ $client->id }}">
                                    <th scope="row">{{ $client->id }}</th>
                                    <td>{{ $client->tax_name }}</td>
                                    <td>{{ $client->tax_code }}</td>
                                    <td>{{ $client->created_at->format('Y-m-d') }}</td>
                                    <td>
                                        <a href="{{ route('clients.edit', $client->id) }}">
                                            <button class="btn btn-primary btn-sm">
                                                <i class="fa fa-pencil"></i> Editar
                                            </button>
                                        </a>

                                        @if ($client->active)
                                            <a href="{{ route('clients.toggle', $client->id) }}">
                                                <button class="btn btn-warning btn-sm">
                                                    <i class="fa fa-pencil"></i> Inactivar
                                                </button>
                                            </a>
                                        @else
                                            <a href="{{ route('clients.toggle', $client->id) }}">
                                                <button class="btn btn-success btn-sm">
                                                    <i class="fa fa-pencil"></i> Activar
                                                </button>
                                            </a>
                                        @endif

                                        <button class="btn btn-danger btn-sm btn-delete" type="button">
                                            <i class="fa fa-times"></i> Eliminar
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $clients->appends(['description' => $description, 'q' => $q])->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {!! Form::open(['route' => ['clients.destroy',':ROW_ID'], 'method' => 'DELETE',
                                  'id' => 'form-delete']) !!}
@endsection

@section('js')
    @include('partials.row_destroy')
@endsection