routes/web.php
Route::get('login', ['as' => 'login.page.show', 'uses' => 'AuthController@loginPage']);
Route::post('login', ['as' => 'login.page.do', 'uses' => 'AuthController@loginAttempt']);
Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);
/*
|--------------------------------------------------------------------------
| Dash Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::get('/', 'HomeController@index');
/*
/*
|--------------------------------------------------------------------------
| Permission Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('permissions', 'PermissionsController');
/*
|--------------------------------------------------------------------------
| Roles Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('roles', 'RolesController');
/*
|--------------------------------------------------------------------------
| Users Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::resource('users', 'UsersController');
/*
|--------------------------------------------------------------------------
| Cities Routes
|--------------------------------------------------------------------------
*/
Route::resource('departments/{department_id}/cities', 'CitiesController');
/*
|--------------------------------------------------------------------------
| Departments Routes
|--------------------------------------------------------------------------
*/
Route::resource('departments', 'DepartmentsController');

/*
|--------------------------------------------------------------------------
| Clients Routes
|--------------------------------------------------------------------------
*/
Route::get('clients/{id}/toggle/', 'ClientsController@toggleClients')->name("clients.toggle");
Route::get('clients/get_client_code', 'ClientsController@getLastClientCode');
Route::post('clients/add_sales', 'ClientsController@addClientBySale');
Route::get('clients/search/{idnum}', 'ClientsController@searchClient');
Route::resource('clients', 'ClientsController');
/*
|--------------------------------------------------------------------------
| Brands Routes
|--------------------------------------------------------------------------
*/
Route::resource('brands', 'BrandsController');
/*
|--------------------------------------------------------------------------
| Metrics Units Routes
|--------------------------------------------------------------------------
*/
Route::resource('metrics', 'MetricsController');
/*
|--------------------------------------------------------------------------
| Categories Routes
|--------------------------------------------------------------------------
*/
Route::resource('categories', 'CategoriesController');
/*
|--------------------------------------------------------------------------
| Providers Routes
|--------------------------------------------------------------------------
*/
Route::get('providers/search/{id}', 'ProvidersController@searchProvider');
Route::resource('providers', 'ProvidersController');
/*
|--------------------------------------------------------------------------
| Products Routes
|--------------------------------------------------------------------------
*/
Route::get("products/find_price/{id}/{list_id}", 'ProductsController@findSellProductsDetails');
Route::get('products/find_product/{id}', 'ProductsController@findProductDetails');
Route::resource('products', 'ProductsController');
/*
|--------------------------------------------------------------------------
| Pricing List Routes
|--------------------------------------------------------------------------
*/
Route::post('all_products', ['as' => 'all.products', 'uses' => 'PricingListController@salesProducts']);
Route::patch('pricing/update', 'PricingListController@updateList');
Route::resource('pricing', 'PricingListController');
/*
|--------------------------------------------------------------------------
| Branches Routes
|--------------------------------------------------------------------------
*/
Route::resource('branches', 'BranchesController');
/*
|--------------------------------------------------------------------------
| Payments Form Routes
|--------------------------------------------------------------------------
*/
Route::resource('payments_forms', 'PaymentsFormController');
/*
|--------------------------------------------------------------------------
| Currencies Routes
|--------------------------------------------------------------------------
*/
Route::resource('currencies', 'CurrenciesController');
/*
|--------------------------------------------------------------------------
| Purchases Routes
|--------------------------------------------------------------------------
*/
Route::post('purchases/payments/submit', ['as' => 'purchases.voucher.submit', 'uses' => 'PurchasesController@paymentVouchersConfirmationSubmit']);
Route::post('purchases/payments/confirmation', ['as' => 'purchases.payments.confirmation', 'uses' => 'PurchasesController@paymentVouchersConfirmation']);
Route::get('purchases/payments', ['as' => 'purchases.payments', 'uses' => 'PurchasesController@paymentVouchers']);
Route::get('purchases/{id}/voucher/cancel', ['as' => 'purchases.voucher.cancel', 'uses' => 'PurchasesController@cancelVoucher']);
Route::post('purchases/{id}/voucher', ['as' => 'purchases.voucher', 'uses' => 'PurchasesController@registerVoucherPayment']);
Route::get('purchases/{id}/voucher', ['as' => 'purchases.voucher.show', 'uses' => 'PurchasesController@showRegisterVoucher']);
Route::resource('purchases', 'PurchasesController');
/*
|--------------------------------------------------------------------------
| Stock Routes
|--------------------------------------------------------------------------
*/
Route::post("stocks/update", 'StocksController@stockAdjustment');
Route::resource('stocks', 'StocksController', ['except' => 'show']);
/*
|--------------------------------------------------------------------------
| Selling Routes
|--------------------------------------------------------------------------
*/
Route::get('sales/create2', 'SalesController@newSalesMethod')->name('sales.create.two');
Route::post('sales/payments/submit', ['as' => 'sales.voucher.submit', 'uses' => 'SalesController@paymentVouchersConfirmationSubmit']);
Route::post('sales/payments/confirmation', ['as' => 'sales.payments.confirmation', 'uses' => 'SalesController@paymentVouchersConfirmation']);
Route::get('sales/payments', ['as' => 'sales.payments', 'uses' => 'SalesController@paymentVouchers']);
Route::get('sales/{id}/voucher/cancel', ['as' => 'sales.voucher.cancel', 'uses' => 'SalesController@cancelVoucher']);
Route::get('sales/{id}/refund', ['as' => 'sales.refund', 'uses' => 'SalesController@showSalesRefund']);
Route::post('sales/{id}/refund', ['as' => 'sales.refund.do', 'uses' => 'SalesController@doSalesRefund']);
Route::post('sales/{id}/voucher', ['as' => 'sales.voucher', 'uses' => 'SalesController@registerVoucherPayment']);
Route::get('sales/{id}/voucher', ['as' => 'sales.voucher.show', 'uses' => 'SalesController@showRegisterVoucher']);
Route::get('sales/print/{id}', ['as' => 'sales.print', 'uses' => 'SalesController@printInvoice']);
Route::resource('sales', 'SalesController');
/*
|--------------------------------------------------------------------------
| Companies Routes
|--------------------------------------------------------------------------
*/
Route::get('companies/get_number/{id}', 'CompaniesController@getNumber');
Route::resource('companies', 'CompaniesController');

/*
|--------------------------------------------------------------------------
| Reports Routes
|--------------------------------------------------------------------------
*/
Route::get('reports/purchases/', ['as' => 'reports.purchases', 'uses' => 'ReportsController@purchases']);
Route::get('reports/refunds/', ['as' => 'reports.refunds', 'uses' => 'ReportsController@refunds']);
Route::get('reports/pricing/', ['as' => 'reports.pricing', 'uses' => 'ReportsController@pricing']);
Route::get('reports/products/', ['as' => 'reports.products.all', 'uses' => 'ReportsController@allProducts']);
Route::get('reports/providers/credit', ['as' => 'reports.providers.credit', 'uses' => 'ReportsController@providersWithCredit']);
Route::get('reports/clients/credit', ['as' => 'reports.clients.credit', 'uses' => 'ReportsController@clientsWithCredit']);
Route::get('reports/products/provider', ['as' => 'reports.products.provider', 'uses' => 'ReportsController@productsByProvider']);
Route::get('reports', ['as' => 'reports.index', 'uses' => 'ReportsController@index']);
Route::get('reports/sales', ['as' => 'reports.sales', 'uses' => 'ReportsController@sales']);
Route::get('reports/day', ['as' => 'reports.sales.day', 'uses' => 'ReportsController@daySales']);
Route::get('reports/products/history', ['as' => 'reports.products.history', 'uses' => 'ReportsController@productHistory']);
Route::get('reports/sales/day', ['as' => 'reports.sales.day', 'uses' => 'ReportsController@daySales']);
Route::get('reports/salesman/commissions', ['as' => 'reports.salesman.commissions', 'uses' => 'ReportsController@getSalesmanCommissions']);
Route::get('reports/users/commissions', ['as' => 'reports.users.commissions', 'uses' => 'ReportsController@getUsersCommissions']);
Route::get('reports/cashiers/movements', ['as' => 'reports.cashiers.movements', 'uses' => 'ReportsController@cashierStatus']);

/*
|--------------------------------------------------------------------------
| Banks Routes
|--------------------------------------------------------------------------
*/
Route::resource('banks', 'BanksController');

/*
|--------------------------------------------------------------------------
| Salesman Routes

app/Models/Products.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{

    protected $table = 'products';

    protected $fillable = ['description', 'title', 'bar_code', 'metric_unit_id', 'brand_id',
        'category_id', 'active', 'commission_percentage', 'salesman_id'];

    public function purchase()
    {
        return $this->hasMany('App\Models\PurchasesDetails', 'product_id');
    }

    public function pricing()
    {
        return $this->hasMany('App\Models\PricingDetails', 'product_id');
    }

    public function categories()
    {
        return $this->belongsTo('App\Models\Categories', 'category_id');
    }

    public function stock()
    {
        return $this->hasMany('App\Models\Stocks', 'product_id');
    }

    public function brands()
    {
        return $this->belongsTo('App\Models\Brands', 'brand_id');
    }

}

resources/views/products/create.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="{{ url('/') }}">Inicio</a></li>
            <li><a href="{{ route('pricing.index') }}">Precios</a></li>
            <li class="active">Nuevo</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Nuevo Producto</strong>
                    </div>
                    <div class="card-body">
                        <!-- Credit Card -->
                        <div id="pay-invoice">
                            <div class="card-body">
                                {!! Form::open(['route' => ['products.store', 'method' => 'post']]) !!}
                                @include('products.partials.fields')
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-paper-plane-o"></i>&nbsp;
                                        <span id="payment-button-amount">Guardar</span>
                                    </button>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>

                    </div>
                </div> <!-- .card -->

            </div><!--/.col-->
        </div>
    </div>

@endsection

@section('css')
    <link rel="stylesheet" href="{{ '/assets/css/selectize.css' }}">
@endsection

@section('js')
    <script type="text/javascript" src="{{ '/assets/js/selectize.js' }}"></script>
    <script>
        $('#select_categories').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $categoriesJson !!}
        });

        $('#select_metric_unit').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $metricsUnitJson !!}
        });

        $('#select_brand').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $brandsJson !!}
        });

        {{--$('#select_branches').selectize({--}}
            {{--delimiter: ',',--}}
            {{--persist: false,--}}
            {{--openOnFocus: true,--}}
            {{--valueField: 'id',--}}
            {{--labelField: 'description',--}}
            {{--searchField: 'description',--}}
            {{--maxItems: 1,--}}
            {{--render: {--}}
                {{--item: function (item, escape) {--}}
                    {{--return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';--}}
                {{--}--}}
            {{--},--}}
            {{--options: {!! $branchesJson !!}--}}
        {{--});--}}
    </script>
@endsection

resources/views/products/edit.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="{{ url('/') }}">Inicio</a></li>
            <li><a href="{{ route('products.index') }}">Productos</a></li>
            <li class="active">Editar</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Editar Producto</strong>
                    </div>
                    <div class="card-body">
                        <!-- Credit Card -->
                        <div id="pay-invoice">
                            <div class="card-body">
                                {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch']) !!}
                                    @include('products.partials.fields')
                                <div>
                                    <button id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
                                        <i class="fa fa-paper-plane-o"></i>&nbsp;
                                        <span id="payment-button-amount">Guardar</span>
                                    </button>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>

                    </div>
                </div> <!-- .card -->

            </div><!--/.col-->
        </div>
    </div>

@endsection

@section('css')
    <link rel="stylesheet" href="{{ '/assets/css/selectize.css' }}">
@endsection

@section('js')
    <script type="text/javascript" src="{{ '/assets/js/selectize.js' }}"></script>
    <script>
        $('#select_categories').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $categoriesJson !!}
        });

        $('#select_metric_unit').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $metricsUnitJson !!}
        });

        $('#select_brand').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $brandsJson !!}
        });
    </script>
@endsection

resources/views/products/index.blade.php
@extends('partials.layout')

@section('breadcrumbs')
    <div class="page-header float-right">
        <ol class="breadcrumb text-right">
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Productos</a></li>
            <li class="active">Inicio</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="animated fadeIn">

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="col-md-11">
                            <strong class="card-title">Filtros de Busqueda</strong>
                        </div>
                        <div class="col-md-1">
                            <a href="{{ route('products.create') }}">
                                <button class="btn btn-danger btn-sm">
                                    <i class="fa fa-plus"></i> Nuevo
                                </button>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('products.index') }}">
                            <input type="hidden" name="q" value="q">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cc-payment" class="control-label mb-1">Nombre</label>
                                        {!! Form::text('title', null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cc-payment" class="control-label mb-1">Categoría</label>
                                        {!! Form::text('category_id', null, ['id' => 'select_categories']) !!}
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cc-payment" class="control-label mb-1">Marca</label>
                                        {!! Form::text('brand_id', null, ['id' => 'select_brands']) !!}
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="client_name" class="control-label mb-1">Estado del Producto:</label>
                                        {!! Form::select('active',[0 => 'Seleccione', 1 => 'Activo', 2 => 'Inactivo'], null, ['class' => 'form-control']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-success btn-sm">
                                        <i class="fa fa-search"></i> Filtrar
                                    </button>
                                    <a href="{{ route('products.index') }}" class="btn btn-warning btn-sm"><i
                                                class="fa fa-reply-all"></i> Ver Todos</a>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="col-md-11">
                            <strong class="card-title">Productos</strong>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Estado</th>
                                <th scope="col">Categoría</th>
                                <th scope="col">Creado</th>
                                <th scope="col">Ultima Modificación</th>
                                <th scope="col">Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($products as $product)
                                <tr data-id="{{ $product->id }}">
                                    <th scope="row">{{ $product->id }}</th>
                                    <td>{{ $product->title }}</td>
                                    <td>{{ $product->active ? 'Activo' : 'Inactivo' }}</td>
                                    <td>{{ $product->categories->description }}</td>
                                    <td>{{ $product->created_at->format('Y-m-d') }}</td>
                                    <td>{{ $product->updated_at->format('Y-m-d') }}</td>
                                    <td>
                                        <a href="{{ route('products.edit', $product->id) }}">
                                            <button class="btn btn-primary btn-sm">
                                                <i class="fa fa-pencil"></i> Editar
                                            </button>
                                        </a>

                                        <button class="btn btn-danger btn-sm btn-delete" type="button">
                                            <i class="fa fa-times"></i> Eliminar
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $products->appends(['title' => $title, 'q' => $q, 'category_id' => $category_id,
                        'brand_id' => $brand_id, 'active' => $active])->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {!! Form::open(['route' => ['products.destroy',':ROW_ID'], 'method' => 'DELETE',
                                  'id' => 'form-delete']) !!}
@endsection

@section('css')
    <link rel="stylesheet" href="{{ '/assets/css/selectize.css' }}">
@endsection

@section('js')
    @include('partials.row_destroy')
    <script type="text/javascript" src="{{ '/assets/js/selectize.js' }}"></script>
    <script>
        $('#select_categories').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $categoriesJson !!}
        });

        $('#select_brands').selectize({
            delimiter: ',',
            persist: false,
            openOnFocus: true,
            valueField: 'id',
            labelField: 'description',
            searchField: 'description',
            maxItems: 1,
            render: {
                item: function (item, escape) {
                    return '<div><span class="label label-primary">' + escape(item.description) + '</span></div>';
                }
            },
            options: {!! $brandsJson !!}
        });
    </script>
@endsection